export const groups = [
  ['vivienda','Vivienda',260,180,'#b21f48'], ['demografia','Demografía',800,180,'#7547a6'], ['pensiones','Pensiones y finanzas públicas',1360,180,'#9d6600'],
  ['educacion','Educación',230,400,'#267347'], ['empleo','Empleo',690,410,'#b21f48'], ['instituciones','Justicia e instituciones',1130,410,'#2464a2'],
  ['movilidad','Movilidad',230,630,'#2464a2'], ['productividad','Productividad',780,650,'#2464a2'], ['turismo','Turismo',1410,440,'#16776e'],
  ['energia','Energía',230,860,'#137e91'], ['agua','Agua y clima',250,1100,'#267347'], ['innovacion','Ciencia e innovación',800,1080,'#963482'],
  ['sanidad','Sanidad',1400,650,'#b21f48'], ['cuidados','Cuidados',1370,870,'#7547a6'], ['agro','Alimentación y campo',1350,1100,'#a24d16'],
].map(([id,title,x,y,color])=>({id:String(id),title:String(title),x:Number(x),y:Number(y),color:String(color)}));
const definitions: Record<string,string[]> = {
 vivienda:['Precio de vivienda','Incentivo a construir','Oferta disponible','Suelo y permisos'], demografia:['Emancipación','Decisiones familiares','Migración','Envejecimiento'], pensiones:['Deuda nominal','Intereses','Déficit','Cotizaciones','Gasto en pensiones'], educacion:['Aprendizaje','Capacidades'], empleo:['Empleo sostenido','Renta del hogar'], instituciones:['Capacidad administrativa','Reglas previsibles','Confianza'], movilidad:['Transporte útil','Acceso a oportunidades'], productividad:['Inversión','Valor por hora','Margen para invertir'], turismo:['Visitantes','Empleo turístico','Presión residencial'], energia:['Renovables','Red y flexibilidad','Energía utilizable'], agua:['Sequía','Disponibilidad de agua','Extracción'], innovacion:['Investigación','Transferencia'], sanidad:['Atención','Salud y autonomía'], cuidados:['Servicios de apoyo','Tiempo disponible'], agro:['Producción agraria','Renta rural']
};
export const nodes = groups.flatMap(g=>definitions[g.id].map((label,i)=>{
 const positions = definitions[g.id].length===2 ? [[-85,0],[85,35]] : [[-125,-15],[70,-15],[15,65],[-120,105],[90,105]];
 return {id:`${g.id}-${i}`,group:g.id,label,x:g.x+positions[i][0],y:g.y+positions[i][1]};
}));
export type Edge = {from:string;to:string;loop?:string;sign?:string;delay?:boolean};
export const edges: Edge[] = [
 ...['vivienda','productividad','pensiones'].flatMap((g,k)=>[{from:`${g}-0`,to:`${g}-1`,loop:['B1','R1','R2'][k],sign:'+',delay:k===1},{from:`${g}-1`,to:`${g}-2`,loop:['B1','R1','R2'][k],sign:'+',delay:k===0},{from:`${g}-2`,to:`${g}-0`,loop:['B1','R1','R2'][k],sign:k===0?'−':'+'}]),
 ...[
 ['vivienda-3','vivienda-2'],['vivienda-2','demografia-0'],['demografia-0','demografia-1'],['demografia-2','empleo-0'],['demografia-2','turismo-2'],['demografia-3','pensiones-4'],['demografia-3','cuidados-0'],['demografia-3','sanidad-0'],['empleo-0','pensiones-3'],['pensiones-3','pensiones-2'],['pensiones-4','pensiones-2'],['empleo-0','empleo-1'],['empleo-1','demografia-0'],['educacion-0','educacion-1'],['educacion-1','empleo-0'],['educacion-1','productividad-1'],['innovacion-0','innovacion-1'],['innovacion-1','productividad-1'],['productividad-2','innovacion-0'],['cuidados-0','cuidados-1'],['cuidados-1','empleo-0'],['sanidad-0','sanidad-1'],['sanidad-1','empleo-0'],['turismo-0','turismo-1'],['turismo-1','empleo-1'],['turismo-0','turismo-2'],['turismo-2','vivienda-0'],['turismo-0','agua-2'],['energia-0','energia-1'],['energia-1','energia-2'],['energia-2','productividad-1'],['energia-2','agro-0'],['agua-0','agua-1'],['agua-1','agro-0'],['agua-2','agua-1'],['agro-0','agro-1'],['movilidad-0','movilidad-1'],['movilidad-1','empleo-0'],['movilidad-1','demografia-0'],['instituciones-0','vivienda-3'],['instituciones-0','cuidados-0'],['instituciones-1','productividad-0'],['instituciones-2','instituciones-0'],['agro-1','demografia-2'],['empleo-1','vivienda-0'],['vivienda-0','movilidad-1'],['innovacion-1','energia-1'],['energia-2','agua-2'],['agua-1','energia-2'],['sanidad-1','cuidados-0'],['cuidados-1','demografia-1'],['educacion-1','innovacion-0'],['instituciones-0','sanidad-0'],['pensiones-2','instituciones-0'],['turismo-0','movilidad-0'],['agro-1','empleo-1'],['productividad-1','empleo-1'],['demografia-2','vivienda-2'],['instituciones-1','innovacion-0'],['energia-0','agro-0'],['movilidad-0','energia-2'],['agua-0','sanidad-0'],['empleo-0','cuidados-1'],['instituciones-2','productividad-0'],['demografia-3','empleo-0'],['agro-0','agua-2'],['turismo-2','demografia-0'],['innovacion-1','sanidad-0'],['vivienda-3','movilidad-0'],['educacion-0','instituciones-2'],['pensiones-4','empleo-1'],['sanidad-1','educacion-0']
 ].map(([from,to])=>({from,to}))
];
